# Generated by Django 2.2.4 on 2019-08-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20190815_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crew',
            name='avatar',
            field=models.ImageField(blank=True, default='user_image/user_deafult.png', upload_to='crew_avatar', verbose_name='avatar'),
        ),
    ]
